= Vert.x-sync examples

== Getting started, preliminary steps

```
   git clone https://github.com/circlespainter/vertx-examples
   cd vertx-examples
```

== Info

Here you will find examples demonstrating Vert.x-Sync in action.

Vertx-sync allows you to deploy verticles that run using *Fibers*. Fibers are very lightweight threads that can be blocked without blocking a kernel thread.

This enables you to write your verticle code in a familiar synchronous style (i.e. no callbacks or promises or Rx).

As no kernel threads are blocked your application retains the scalability advantages of a non (kernel thread) blocking application.


The examples can be run using the Quasar Agent.

In your IDE you must add the following JVM option in your IDE run configuration:

----
-javaagent:</path/to/the/quasar/jar/>
----

e.g.

----
-javaagent:/Users/fabio/.m2/repository/co/paralleluniverse/quasar-core/0.7.5/quasar-core-0.7.5-jdk8.jar
----

You will also need to configure your IDE to not replace the classes generated in `target/classes` and use them. In IntelliJ, for instance, remove the _Before launch_ `make` action.

== `fiberhandler`

This example demonstrates using a `FiberHandler` to run a standard handler using a Fiber.

In this case the standard handler is an `HttpServer` request handler which sends an event bus message and gets a reply back synchronously after one second before ending the response.

You can run the example in your IDE with the provided `main` method.

With maven instead:

```
mvn install
cd sync-examples
mvn compile exec:exec
```

Then open a browser and point it at `localhost:8080`. Ignore the `UnableToInstrument` exceptions, they're harmless and will go away in a future `vertx-sync` version.

== Fiber scheduler troubleshooting

The `fiberhandler` example has been modified to set a ForkJoin scheduler rather than `vertx-sync`'s direct one. After you hit `http://localhost:8080` with a brower or HTTP client, you'll see on `stdout` a line stating: `[HTTPReqHandler] Running in a fiber, scheduler class: co.paralleluniverse.fibers.FiberForkJoinScheduler`.
The stacktrace will show a regular fiber stacktrace of a task run by the .

You can comment out the `vertx.getOrCreateContext().put(FIBER_SCHEDULER_CONTEXT_KEY, ...)` line in `fiberhandler/Server.java` in order to use the default direct scheduler, in that case you'll see on `stdout` a line stating: `[HTTPReqHandler] Running in a fiber, scheduler class: co.paralleluniverse.fibers.FiberExecutorScheduler`. The stacktrace will show a fiber started by `vertx-sync` and immediately being executed in the very same thread.
